# Generated by Django 5.2.17 on 2026-09-10 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pesagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produto', models.CharField(max_length=100)),
                ('massa', models.DecimalField(decimal_places=3, max_digits=10)),
                ('confianca', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ('quantidade_objetos', models.PositiveIntegerField(default=1)),
                ('data_hora', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
