# Generated by Django 5.2.17 on 2026-09-10 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pesagem',
            name='confianca',
        ),
        migrations.RemoveField(
            model_name='pesagem',
            name='quantidade_objetos',
        ),
        migrations.AddField(
            model_name='pesagem',
            name='contagem',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='pesagem',
            name='quantidade_deteccoes',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
