# Generated by Django 5.2.17 on 2026-09-17 11:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_pesagem_confianca_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pesagem',
            name='contagem',
        ),
        migrations.RemoveField(
            model_name='pesagem',
            name='produto',
        ),
        migrations.RemoveField(
            model_name='pesagem',
            name='quantidade_deteccoes',
        ),
        migrations.AddField(
            model_name='pesagem',
            name='frames_analisados',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pesagem',
            name='objetos_rastreados',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='ItemPesagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classe', models.CharField(max_length=100)),
                ('quantidade', models.PositiveIntegerField()),
                ('confianca_media', models.FloatField(blank=True, null=True)),
                ('razao_votacao', models.FloatField(blank=True, null=True)),
                ('pesagem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='app.pesagem')),
            ],
        ),
    ]
